/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   tutorialSidebar: [
//     {type: 'autogenerated', dirName: '.'}
//   ]
// };

const sidebars = {
  programSidebar: [
    'intro',
    {
      type: 'category',
      label: '程式語言',
      items: [
        {
          type: 'category',
          label: 'HTML & CSS',
          items: [
            {type: 'autogenerated', dirName: 'language/HTML'}
          ]
        },
        {
          type: 'category',
          label: 'JavaScript',
          items: [
            {type: 'autogenerated', dirName: 'language/JavaScript'}
          ]
        },
        {
          type: 'category',
          label: 'TypeScript',
          items: [
            {type: 'autogenerated', dirName: 'language/TypeScript'}
          ]
        },
        {
          type: 'category',
          label: 'SQL',
          items: [
            {type: 'autogenerated', dirName: 'language/SQL'}
          ]
        },
        {
          type: 'category',
          label: 'Python',
          items: [
            {type: 'autogenerated', dirName: 'language/Python'}
          ]
        },
        {
          type: 'category',
          label: 'Dart',
          items: [
            {type: 'autogenerated', dirName: 'language/Dart'}
          ]
        }
      ]
    },
    {
      type: 'category',
      label: '開發框架',
      items: [
        {
          type: 'category',
          label: 'React',
          items: [
            {type: 'autogenerated', dirName: 'framework/React'}
          ]
        },
        {
          type: 'category',
          label: 'Vue3',
          items: [
            {type: 'autogenerated', dirName: 'framework/Vue'}
          ]
        },
        {
          type: 'category',
          label: 'Docusaurus',
          items: [
            {type: 'autogenerated', dirName: 'framework/Docusaurus'}
          ]
        },
      ]
    },
    {
      type: 'category',
      label: '演算法',
      items: [
        {type: 'autogenerated', dirName: 'algorithm'}
      ]
    },
    {
      type: 'category',
      label: '開發日誌',
      items: [
        {type: 'autogenerated', dirName: 'dev-note'}
      ]
    }
  ],
  novelSidebar: [
    'novel-intro',
    {
      type: 'category',
      label: '蛇與魔杖',
      items: [
        {
          type: 'autogenerated',
          dirName: 'bookshelf/蛇與魔杖'
        }
      ]
    },
    {
      type: 'category',
      label: '神鋒',
      items: [
        {
          type: 'autogenerated',
          dirName: 'bookshelf/神鋒'
        }
      ]
    }
  ]
};

export default sidebars;
