// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  programSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tech_articles'
    }
  ],
  thirtySeriesSidebar: [
    {
      type: 'autogenerated',
      dirName: '30_day_series'
    }
  ]
};

export default sidebars;
