name: Deploy to GitHub Pages

on:
  push:
    branches:
      - action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          GIT_USER=chungyingho npm run deploy
        env:
          DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }}
